### PR TITLE
Project initialization

### PR DESCRIPTION
**Pull request by oakensoul**
- Uses carbonite/viper-dev Vagrant Box
- Vagrant file to spin up the dev environment
- Added Gulp for task management
- Added License
- Added Travis support
- Added Contributing and Readme docs

### CODE REVIEW

**Comment by oakensoul** [comment]
@all please review

**Comment by Seshra** [comment]
+1

**Comment by asagage** [comment]
+1

**Comment by rongway** [comment]
:+1:

**Pull request merged**
